### ISSUE TITLE
Printing and storing unrooted trees as Newick format

### ISSUE THREAD

**Issue by mbrazeau** [mbrazeau/Morphy#12]
Functions now play nice with unrooted tree as far as not crashing goes, but we need our Newick-writing functions to print correctly when passed an unrooted tree. The proposed solution is to impose an arbitrary root.

**Comment by TGuillerme** [comment]
All newick printing functions are running in `mfl_newick.c`. Testing is done in `tui/main.c` `tui_test_newick_stuff()`.

`mfl_convert_mfl_tree_t_to_newick()`
`mfl_tree_from_newick_to_buffer(()`
